spring:
  datasource:
    url: jdbc:mysql://p1us8ottbqwio8hv.cbetxkdyhwsb.us-east-1.rds.amazonaws.com/cu88avxv59nt333y?reconnect=true
    username: anpykrycx5b9ef61
    password: f8govccpt4h30qmo

flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

swagger:
  protocol: https
